### ISSUE TITLE
error captive portal personalizado

### ISSUE THREAD

**Issue by aytachdede** [jjamor/pfsense-cpsamplepages#1]

**Comment by aytachdede** [comment]
este captive portal personalizado esta muy amigable y bastante sencillo preparado sin embargo al rato de conectar a la red con un equipo portatil ( no moviles) se queda la pagina  existe algun error en el archivo login.php 
no soy experto en esto pero qeria reportarlo 
saludos

**Comment by aytachdede** [comment]
se lo agredeceria si me ayuda corregiendo el error que mencione
tambien si pone un campo adicional para los usuarios con voucher 
ya que pfsense funciona freeradius + voucher sin ningun problema (hasta 2.2.5 he probado sin ningun problema)
para tener este opcion tambien
saludos

**Comment by jjamor** [comment]
Hello, I must review php pages for authenticated and voucher portals. Stay tuned ;)

**Comment by aytachdede** [comment]
I hope you give hand to do many thanks
Also non mobile browser has been problem actually
Many thanks for sharing

On Sat, May 14, 2016 at 8:38 AM -0700, "Juan Jose Amor Iglesias" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello, I must review php pages for authenticated and voucher portals. Stay tuned ;)

##

**Comment by jjamor** [comment]
Hi,

Just commited a fix for this. Currently I have not tested with vouchers, but with authenticated portals.

Could you thest this commit? (e9bb607)

Many thanks!
